### ISSUE TITLE
error

### ISSUE THREAD

**Issue by charugaa** [nzfarmer1/mqtt2opcua#10]
root@node-red:/opt/mqtt2opcua# node examples/run.js
OPC Server Initialized
Error: expecting a valid port (number)
    at OPCUAServer.createEndpointDescriptions (/opt/mqtt2opcua/node_modules/node-opcua-server/dist/opcua_server.js:2379:19)
    at OPCUAServer.<anonymous> (/opt/mqtt2opcua/node_modules/node-opcua-server/dist/opcua_server.js:558:39)
    at Generator.next (<anonymous>)
    at /opt/mqtt2opcua/node_modules/node-opcua-server/dist/opcua_server.js:15:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/mqtt2opcua/node_modules/node-opcua-server/dist/opcua_server.js:11:12)
    at OPCUAServer._delayInit (/opt/mqtt2opcua/node_modules/node-opcua-server/dist/opcua_server.js:531:33)
    at OPCUAServer.<anonymous> (/opt/mqtt2opcua/node_modules/node-opcua-server/dist/opcua_server.js:674:28)
    at Generator.next (<anonymous>)
    at /opt/mqtt2opcua/node_modules/node-opcua-server/dist/opcua_server.js:15:71

**Comment by henjoe** [comment]
Hi, I don't know if you already solve this.
Simply make this configuration under run.js as number (simply remove the double quoation mark)

![image](https://user-images.githubusercontent.com/49782655/202880212-38ed1711-1c76-46be-8119-33c32a0782ee.png)

Have you run your server successfully? I am having error too.
